import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اختر اللغة",
          "2": "البريد الالكتروني",
          "3": "نحن لدينا 100 الف منتج  , اختر \n  منتجك  من  متجرنا",
          "4": "سهل وامن للشراء",
          "5": "يمكنك الدفع كاش او \n من خلال بوابات الدفع الالكترونية",
          "6": "تتبع طلبك",
          "7": "يمكنك تتبع طلبك في كل مرحلة \n وايضا التتبع من خلال الخريطة",
          "8": "متابعه",
          "9": "تسجيل الدخول",
          "10": "اهلا بك",
          "11":
              "يمكنك تسجيل الدخول من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "12": "ادخل البريد الالكتروني",
          "13": "ادخل كلمة المرور",
          "14": "هل نسيت كلمة المرور",
          "15": "تسجيل الدخول",
          "16": "ليس لديك حساب ? ",
          "17": "انشاء حساب",
          "18": "البريد الالكتروني",
          "19": "كلمة المرور",
          "20": "اسم المستخدم",
          "21": "رقم الهاتف",
          "22": "ادخل رقم الهاتف",
          "23": "ادخل اسم المستخدم",
          "24":
              "انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "25": " لديك حساب ? ",
          "26": "تسجيل الدخول",
          "27": "فحص البريد الالكتروني",
          "28": "تم انشاء الحساب بنجاح",
          "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
          "30": "فحص",
          "31": "الذهاب لتسجيل الدخول",
          "32": "نجاح",
          "33": "حفظ",
          "34": "الرجاء ادخال كلمة المرور الجديدة",
          "35": "الكلمة الجديدة",
          "36": "تم اعادة تعيين كلمة المرور بنجاح",
          "37": "تهانينا",
          "38": "تم التسجيل بنجاح",
          "39": "الفواكة",
          "40": "الخضروات",
          "41": "المكسرات",
          "42": "اللحوم والاسماك",
          "43": "كل الحبوب",
          "44": "الالبان",
          "45": "الزيوت",
          "46": "البذور",
          "47": "الدهون المشبعة",
          "48": "البقوليات",
          "49": "الاقسام",
          "50":
              "الخضار من المواد الغذائيّة التي تتميّز بقلّة نسبة الدهون بها، وإذا وجدت في بعض الأصناف فإنّها تكون من الدهون سهلة الامتصاص؛ إذ يكون مصدرها الألياف، وتعتبر الخضار مصدراً للمواد الكربوهيدراتيّة الأساسية التي تزود الجسم بالطاقة. الخضار غنية بمادة الحديد التي تتوفر في البقوليّات. احتواء الخضار على نسب عالية من الماء يعطي الجسم فوائد عديدة مثل: تسهيل عملية الهضم، والليونة لأعضاء الجسم. أهم ما تحتويه الخضار مادّة السليولوز التي لا يمتصّها الجسم؛ بل تبقى داخل الأمعاء فينشط عملها، وتعمل كمليّن طبيعي للجهاز الهضمي، كما ينشط عمل الغدد لإفراز الإنزيمات الخاصّة بالهضم",
          "51": "الخضروات غير النشوية",
          "52":
              "تعد الخضروات غير النشوية ضمن أغذية صحية لمرضى السكري، وهي تشمل قائمة الخضروات غير النشوية: البروكلي والجزر ,الخرشوف الكرفس, الخيار والبصل. تعد الخضروات غير النشوية مصدرًا جيدًا للألياف الغذائية، والتي يمكنها في العموم أن تساعد في إبطاء امتصاص السكر في مجرى الدم، كما أنها تحتوي على فيتامينات ومعادن ومضادات أكسدة مفيدة لصحتك العامة، وهي كذلك منخفضة السعرات الحرارية والكربوهيدرات",
          "53": "الخيار",
          "54":
              "يعد الخيار من الخضروات الجيدة لمرضى السكري الذين يعانون من ارتفاع في مستوى السكر، فهو يحتوي على سعرات حرارية منخفضة ومحتوى عالي من الألياف",
          "55":
              "كما قد يساعد الخيار في خفض نسبة السكر في الدم لاحتوائه على هرمون تحتاجه خلايا بيتا لإنتاج الأنسولين.",
          "56": "الطماطم",
          "57":
              "الطماطم (البندورة) هي طعام لا يسبب ارتفاعًا في مستويات السكر في الدم. تعد الطماطم أيضًا مصدرًا جيدًا للألياف والفيتامينات A و C، والتي هي هامة لمريض السكر. الألياف الغذائية تساعد على إبطاء امتصاص السكر في مجرى الدم، والفيتامينات A و C من مضادات الأكسدة التي تساعد في حماية الخلايا المختلفة بالجسم من التلف. لكل ما سبق تعد الطماطم من ضمن أفضل الأطعمة لمرضى السكري",
          "58": "البروكلي",
          "59":
              "يحتوي البروكلي على مركب السلفورافان الذي يخفض نسبة السكر في الدم بشكل طبيعي",
          "60":
              "خلصت إحدى الدراسات العلمية إلى أن خضار البروكلي الذي يحتوي على مركب السلفورافان الذي يقلل من علامات الإجهاد التأكسدي، ومستوى السكر في الدم، كما أنه يعزز من حساسية الأنسولين.",
          "61": "السبانخ",
          "62":
              "يحتوي السبانخ على الكثير من الفيتامينات، والألياف، والبروتين، والكاروتين، والمعادن المغذية لمرضى السكري، يعود السبب الذي قد يجعلك تختار تناول السبانخ في حال كنت تعاني من ارتفاع مستوى السكر في الدم، هو أن مؤشر نسبة السكر في الدم فيه تبلغ صفر",
          "63": "الهليون",
          "64":
              "يحتوي الهليون على كمية منخفضة جدًا من الكربوهيدرات ما يقارب 7 غرام لكل كوب، الأمر الذي يجعله ملائمًا لمرضى السكري الذين يرغبون في تخفيض مستوى السكر لديهم",
          "65": "الخضروات الورقية",
          "66":
              "هناك علاقة وثيقة بين تناول حصتين إلى ثلاث حصص من الخضار الورقية في الأسبوع وانخفاض احتمالية الإصابة ببعض أنواع السرطان وأمراض القلب والسكري.تساعد هذه الخضار في الحفاظ على استقرار نسبة السكر في الدم، كما يساهم تناول كوب واحد من الخضروات الورقية الخضراء يوميًا في خفض خطر الإصابة بمرض السكري بنسبة 14%",
          "67":
              "بما انك مريض سكري، فقد تتساءل عما إذا كانت الفاكهة محظورة عليك؟ والجواب هو أنه يمكنك تناول أنواع معينة من الفاكهة باعتدال. الفاكهة بشكل عام مصدر كبير للعناصر الغذائية والألياف ومضادات الأكسدة. تشمل قائمة أفضل 10 فواكه لمرضى السكري: الفواكه الحمضية مثل البرتقال، التفاح، التوت بأنواعه مثل التوت الأزرق والتوت البري، الفراولة، الأفوكادو، الخوخ، البرقوق، الكرز، الكمثرى",
          "68": "التوت",
          "69":
              "تعد فاكهة التوت من الفواكه الغنية بالفيتامينات والألياف ومضادات الأكسدة مما يجعلها من الفواكه المفيدة لمرضى السكري حيث تساعد في تخفيف حساسية الأنسولين وتقليل كمية الغلوكوز في جسم الإنسان,كما يعد تناول كوبين من التوت أي ما يعادل 250 غرام من التوت بأنه يساهم في تقليل كمية السكر في الدم",
          "70": "الحمضيات",
          "71":
              "إنَّ فاكهة البرتقال والجريب فروت وغيرها من الحمضيات غنية بالألياف والمركبات النباتية مثل البوليفينول والنارينجين التي تعد مضادات لمرض السكري,حيث تقلل الحمضيات من نسبة الإصابة بمرض السكري لأنها لا ترفع نسبة السكر في الدم كما تعمل بعض الفاكهة الأخرى",
          "72": "التفاح",
          "73":
              "يحتوي التفاح على مركبات نباتية مهمة مثل: حمض الكلوروجينيك، والكيرسيتين ، تساعد هذه المركبات في تقليل نسبة السكر في الدم كما تحمي الجسم من الإصابة بمرض السكري",
          "74": "قد يساعد تناول المكسرات في السيطرة على مستويات السكر في الدم لدى مرضى السكري وهي بشكل عام أحد أفضل الأطعمة لمرضى السكري؛ فالمكسرات مصدر جيد للبروتين والألياف والدهون الصحية، كما أنها تحتوي على المغنيسيوم، وهو معدن يساعد في تنظيم مستويات السكر في الدم. من أهم أنواع المكسرات المفيدة لمرضى السكر: الجوز، المكسرات البرازيلية، الكاجو، البندق",
          "75": "على الرغم من احتواء المكسرات على نسبة عالية من الدهون والسعرات الحرارية، إلا أن تناولها باعتدال قد يساعد على منع زيادة الوزن وإبقاء الوزن تحت السيطرة والحفاظ عليه ضمن مستويات صحية والسبب في ذلك يعزى غالبًا لقدرة المكسرات المحتملة على كبح الشهية، وتعزيز الشعور بالشبع لساعات أطول، مما قد يقلل من الرغبة في تناول كميات إضافية من الطعام الغني بالسعرات. ولكن يجب التنويه إلى ضرورة تناول المكسرات باعتدال، لأن الإفراط في تناولها قد يسبب زيادة الوزن",
          "76": "استخدام المكسرات كبديل صحي عن بعض الوجبات عالية السعرات، بدلًا عن إضافتها للحمية الغذائية كوجبات جانبية تناول حصة معتدلة فقط من المكسرات يوميًّا، وتعادل الحصة المسموحة تقريبًا حفنة صغيرة من المكسرات في قبضة اليد",
          "77": "الفستق الحلبي ",
          "78": " أظهرت إحدى الدراسات أن تناول الفستق الحلبي من قبل الأشخاص المصابين بمرض السكري من النوع الثاني قد يساعد على تحسين الحالة الصحية العامة لديهم والسبب في ذلك يعزى غالبًا لغنى هذا النوع من المكسرات بالمغنيسيوم، ومجموعة متنوعة من مضادات الأكسدة التي قد تساعد على الآتي: ابطاء وتيرة ارتفاع سكر الدم تقليل الالتهاب كبح الشهية ",
          "79": "الجوز",
          "80": "قد يكون للجوز العديد من الفوائد المحتملة لمرضى السكري وللأشخاص الذين يرغبون في خفض فرص إصابتهم بمرض السكري، وهذا ما تقوله الدراسات في هذا الصدد: أظهرت إحدى الدراسات أن تناول الجوز قد يساعد على تعزيز الشعور بالشبع، وتحفيز خسارة الوزن الزائد، مما قد يسهم في الحماية من السمنة أظهرت دراسة أخرى أن قيام النساء بتناول الجوز بانتظام قد يساعد على خفض فرص إصابتهن بمرض السكري من النوع الثاني تعزى فوائد الجوز المحتملة في هذا الشأن غالبًا لغنى الجوز بحمض الألفا ليبويك ، وهو أحد الأحماض الهامة التي قد تساعد على تخفيف الالتهابات وبالتالي خفض فرص الإصابة بالعديد من الأمراض المزمنة التي من الممكن للالتهابات أن تحفز الإصابة بها، مثل: مرض الزهايمر، ومرض السكري، وأمراض القلب",
          "81": "اللوز",
          "82": "قد يساعد إعطاء هذا النوع من المكسرات لمرضى السكري على تحسين حالتهم الصحية العامة إذ أظهرت إحدى الدراسات أن تناول القليل من اللوز يوميًّا على مدى 12 أسبوعًا متواصلًا قد يساعد على تنظيم مستويات سكر الدم، وخفض فرص الإصابة بأمراض القلب لدى مرضى السكري من النوع الثاني",
          "83": "الأسماك وخاصة الأسماك الدهنية (مثل: السلمون والتونة والسردين) أحد أفضل أطعمة صحية لمرضى السكر وذلك لما يلي: هذه الأسماك غنية بأحماض أوميغا 3 الدهنية، والتي ثبت أنها تخفض مستويات السكر في الدم وتحسن حساسية الأنسولين تعتبر الأسماك أيضًا مصدرًا جيدًا للبروتين وهي قليلة السعرات الحرارية كما أنها مصدر ممتاز للعديد من الفيتامينات والمعادن، بما في ذلك فيتامين د والسيلينيوم والمغنيسيوم  ",
          "84": "يمكن أن يساعدك البروتين الذي يوجد في الأسماك واللحوم في التحكم في مستويات السكر في الدم وفقدان الوزن يساعد البروتين أيضًا في بناء وإصلاح الأنسجة في جسمك. كذلك البروتين عنصر غذائي مهم لمرضى السكري؛ لأنه يمكن أن يساعد في منع أو إبطاء تقدم مضاعفات مرض السكري، مثل: أمراض الكلى.وأيضا الأسماك مفيدة لصحة القلب  تناوَل الأسماك الصحية المفيدة لصحة القلب مرتيْن على الأقل في الأسبوع. الأسماك، مثل السلمون والماكريل والتونة والسردين، غنية بأحماض  أوميجا 3 الدهنية. وقد تقي أحماض أوميجا 3 الدهنية من الإصابة بمرض القلب. تجنَّب تناول الأسماك المقلية والأسماك التي تحتوي على مستويات عالية من الزئبق، مثل سمك القد ",
          "85": "تعد منتجات الألبان الخالية من الدهون أو قليلة الدسم أحد أفضل الأطعمة لمرضى السكري، حيث توصي جمعية السكري الأمريكية (ADA) مرضى السكري بتناول منتجات الألبان الخالية من الدهون أو قليلة الدسم. تعتبر منتجات الألبان مصدرًا ممتازًا لمعادن الكالسيوم والبوتاسيوم والمغنيسيوم، كما أنها تحتوي على فيتامين (أ) وبعض فيتامينات (ب). من أبرز منتجات الألبان قليلة الدسم أو خالية الدسم المسموح بها لمريض السكر: حليب اللوز غير المحلى، حليب الصويا غير المحلى، الجبن قليل الدسم، كريمة الحليب، الحليب والزبادي خالي الدهن، والأجبان الطبيعية قليلة الدسم.",
          "86": "تتضمن مصادر الكوليستيرول مشتقات الحليب الدسمة والبروتينات الحيوانية الدسمة وصفار البيض . لا تتناول أكثر من 200 ملغم من الكوليستيرول في اليوم.",
          "87": "الدهون الجيدة والمعروفة أيضًا باسم الدهون الصحية، ضرورية لمجموعة متنوعة من الأسباب، فهي تساعدك على امتصاص الفيتامينات وبناء أغشية الخلايا وإنتاج الهرمونات. تساعد الدهون الصحية أيضًا في الحفاظ على استقرار مستويات السكر في الدم، وهذا مهم إذا كنت مصابًا بداء السكري لأن مستويات السكر في الدم غير المستقرة كما هو معروف يمكن أن تؤدي إلى مضاعفات صحية خطيرة بعض المصادر الجيدة للدهون الصحية تشمل: زيت الكانولا وزيت الأفوكادو وزيت الزيتون وزيت جوز الهند.",
          "88": "زيت الزيتون",
          "89": "يلعب زيت الزيتون دورًا مهمًا لمرضى السكر، حيث أنه ذكر في دراسة أن استهلاك زيت الزيتون لمرضى السكر من النوع الثاني يساعد في: التقليل من ارتفاع مستوى السكر في الدم.تحسين مستوى الأنسولين في الدم. تعزيز تحمل الغلوكوز. تحسين حساسية الأنسولين في الدم. تقليل الموت الخلوي للخلايا المسؤولة عن إنتاج الإنسولين. زيادة عدد الخلايا المسؤولة عن تصنيع الإنسولين.",
          "90": "زيت جوز الهند",
          "91": "يعمل زيت جوز الهند على تحفيز إنتاج الأنسولين والتقليل من مستويات مقاومة الأنسولين في الجسم. الحفاظ على استقرار نسب السكر في الدم، وتحفيز الجسم على الاستفادة بطريقة أفضل من غلوكوز الدم. لذا قد يساعد زيت جوز الهند على الوقاية من الإصابة بالسكري، أو تحسين قدرة مريض السكري على إبقاء حالته تحت السيطرة لا سيما المرضى المصابين بالسكري من النمط الثاني.",
          "92": "تعتبر الحبوب الكاملة جزءًا مهمًا من النظام الغذائي الصحي لمرضى السكري؛ فهي غنية بالألياف والعناصر الغذائية المتنوعة، ويمكن أن تساعد في التحكم في مستويات السكر في الدم. تشمل الحبوب الكاملة: القمح الكامل والأرز البني والشوفان والشعير والكينوا والأرز البري، والحنطة السوداء، والبرغل (القمح المجروش)، والدخن. للعلم فإن تناول الأطعمة المحتوية على الألياف الغذائية يعد من ضمن طرق الحفاظ على الجهاز الهضمي. الجدير بالعلم أن للكربوهيدرات كالنشا الموجود في الحبوب أكبر أثر على مستوى السكر في الدم؛ لأنه في النهاية يتم تحليل كل الكربوهيدرات إلى سكر بسيط من قبل الجسم، حيث يحتاج الجسم وقتًا أطول لهضم الكربوهيدرات المعقدة وتحويلها إلى سكر بسيط، وبالتالي فإنها تشكل خيارًا أفضل للجميع وأيضًا لمرضى السكر. كما أن للأشخاص الذين يعانون من مشاكل المتعلقة بمستوى السكر في الدم يوصي الخبراء بالحد من استهلاك الكربوهيدرات من أجل الحفاظ على مستويات سليمة للسكر في الدم، ومع ذلك لا يوصى بإزالة الحبوب تمامًا من النظام الغذائي اليومي، وذلك بسبب فوائد استهلاك الكربوهيدرات في الحمية الغذائية المتوازنة، وإليكم في ما يأتي أهم فوائد الحبوب الكاملة لمرضى السكري: التقليل من خطر الإصابة بمرض السكري من النوع الثاني. التحكم في مستوى السكر في الدم. التقليل من احتمالات الإصابة بمرض السكري.",
          "93": "حبوب القمح الكامل ",
          "94": "يساعد تناول حبوب القمح الكاملة على تنظيم مستويات سكر الدم وإبقائها ضمن مستويات طبيعية وصحية، وذلك بسبب ما تتمتع به من مؤشر جلايسيمي منخفض نسبيًّا. إذ تحتوي الحبوب الكاملة على نسبة عالية من الألياف الغذائية، والألياف هي نوع من أنواع الكربوهيدرات التي قد تساعد على تحسن مستويات سكر الدم للأسباب الآتية:  صعوبة قيام الجسم بهضم الألياف، مما قد يؤدي لإبطاء وتيرة الهضم وإبطاء وتيرة امتصاص المواد الغذائية من الطعام، وبالتالي منع الإصابة برفعات مفاجئة في سكر الدم والحفاظ على مستويات السكر ضمن نطاق صحي.  قدرة الألياف المحتملة على تحسين حساسية الأنسولين في الجسم. كما تعد حبوب القمح الكاملة مصدرًا جيدًا للعديد من المعادن والفيتامينات، مثل: فيتامينات المجموعة ب، وفيتامين هـ، والزنك، والمغنيسيوم.",
          "95": "الشوفان والأرز البني",
          "96": "يعمل الشوفان على خفض مستوى السكر في الدم عن طريق زيادة حساسية الأنسولين، وهذه من أبرز فوائد الشوفان لمرضى الكلى. يعد الأرز البني من الحبوب الكاملة المفيدة لمرضي السكر حيث :  يساعد على تعزيز صحة القلب. يساعد في السيطرة على مرض السكري. يمكن أن يكون له دور في خفض الوزن. يحسن صحة الجسم بشكل عام. يعد مصدر خالٍ من الغلوتين. ",
          "97": "ولكن إذا كنتم ترغبون في محاولة اتباع حمية غذائية خالية من الغلوتين فلا يوجد سبب للتخلي عن الحبوب، حيث يوصي الخبراء معظم الأشخاص الذين يعانون من مشاكل السكر في الدم أن يستهلكوا الحبوب الكاملة، لأنها مغذية ومليئة بالألياف الغذائية، مما يساعد في الحفاظ على مستوى سكر سليم. بذور الكزبرة في الحفاظ على استقرار مستويات السكر في الدم لدى مرضى السكري عن طريق التحكم في إفراز الأنسولين في الجسم. البذور المختلفة لها تأثيرات مختلفة على مستويات السكر بالدم، حيث يمكن أن يساعد البعض منها مثل: بذور الشيا والكتان في التحكم في نسبة السكر في الدم، بينما يمكن أن يتسبب البعض الآخر منها مثل: بذور اليقطين وبذور عباد الشمس في حدوث ارتفاع بسكر الدم. لذا إذا كنت مصابًا بداء السكري، فمن المهم مراقبة تناول البذور واختيار البذور التي لا ترفع نسبة السكر في الدم. قد تتسبب بذور الكتان في مضاعفة تأثير الأدوية الخافضة لسكر الدم والتي يتناولها مريض السكري، الأمر الذي قد يكون ضارًا جدًا لمرضى السكري، لذا يجب عليك عدم استهلاك بذور الكتان. ",
          "98": "يسأل البعض هل البقوليات ترفع السكر؟ وهنا يجب العلم أن البقوليات مثل الفول والبازلاء والعدس، منخفضة في مؤشر نسبة السكر في الدم (GI)، وهذا يعني أن لها تأثيرًا بطيئًا على مستويات السكر في الدم. من أهم البقوليات المفيدة لمرضى السكر سوف نجد الحمص، واللوبيا، والفاصوليا. تُسبب البقوليات أحيانا ارتفاع في مستوى السكر في الدم، فهي تحتوي على جزء كبير من الكربوهيدرات، لذلك يجدر بمرضى السكري الانتباه إلى نظامهم الغذائي تحديدًا عند تضمين البقوليات فيه. كما يُفضل قيامهم بدمج البقوليات مع الخضروات غير النشوية والفواكه منخفضة السكر، والأطعمة الغنية بالبروتين للحصول على وجبة مثالية دون التأثير على مستوى السكر في الدم.",
          "99": "الفاصولياء الحمراء والحمص ",
          "100": "تعد الفاصوليا الحمراء مفيدة لمرضى السكري، إذ تساعد محتوياتها الغذائية الغنية خاصةً الألياف على تنظيم مستويات سكر الدم وإبقائها تحت السيطرة ومنع أي رفعات مفاجئة فيها. الحمص من البقوليات المفيدة جدا لمرضي السكر إذ أن المؤشر الجلايسيمي المنخفض للحمص بأشكاله المختلفة يجعله طعامًا مناسبًا للمحافظة على سكر الدم حتى عند مرضى السكري ويحتوي الحمص على نسبة عالية من الألياف والسكريات بطيئة الهضم، كما يحتوي الحمص على نسبة عالية من البروتينات والكالسيوم والبوتاسيوم وحمض الفوليك.",
          "101": "وجبات الدهون المشبعة",
          "102": "يزيد مرض السكري خطر الإصابة بانسداد الشرايين وتصلبها، مما يجعلك أكثر عرضة للإصابة بأمراض القلب والسكتة الدماغية. ويمكن للأطعمة التي تحتوي على العناصر التالية أن تضر بمحاولتك الالتزام بنظام غذائي صحي مفيد لصحة القلب. الدهون المُشبَّعة: تجنَّب مشتقات الحليب والبروتينات الحيوانية الدسمة، مثل الزبد واللحم البقري والنقانق والسجق ولحم الخنزير المقدد. قلل أيضًا من تناول زيوت جوز الهند وبذور النخيل. الدهون المتحولة. تجنَّب الدهون المتحولة الموجودة في الأطعمة الخفيفة الجاهزة بين الوجبات والمخبوزات والدهون المقصرة (القابلة للخفق) والسَّمن النباتي (المارغرين) الصلب. الكوليسترول. تتضمن مصادر الكوليسترول مشتقات الحليب الدسمة والبروتينات الحيوانية الدسمة وصفار البيض والكبد ولحوم الأحشاء الأخرى. لا تتناول أكثر من 200 ملغم من الكوليسترول في اليوم. الصوديوم. لا تتناول أكثر من 2,300 ملغم من الصوديوم في اليوم. قد يقترح الطبيب تناول كمية أقل إذا كنت مصابًا بارتفاع ضغط الدم.",
          "103": "تعليمات النظام الرياضي",
          "104": "ممارسة النشاط البدني بانتظام له إيجابيات وفوائد كثيرة على صحة الإنسان؛ وخاصة المصابين بالسكري، فهي من العناصر الأساسية لتنظيم نسبة السكر في الدم، وتختلف نوعية التمارين الرياضية باختلاف العمر والجنس والحالة الصحية والمقدرة الفردية ويقوم الطبيب الخاص بك بمتابعه حالتك البدنية حتى يحدد لك التمارين الرياضية المناسبة لك.",
          "105": "فوائد النشاط البدني للمصابين بداء السكري",
          "106": "•	خفض وتنظيم نسبة السكر والدهون في الدم. •	تقليل مقاومة خلايا الجسم للإنسولين. •	زيادة عدد مستقبِلات الإنسولين؛ وبالتالي الاستخدام الأمثل للإنسولين في الجسم. •	تقليل كمية الدواء الذي يستخدمه المريض. •	تقوية وبناء الجسم والعضلات. •	يساعد على تخفيف الوزن والمحافظة على الوزن المثالي. •	تحسين الحالة النفسية. ",
          "107": "تأثير النشاط البدني على سكر الدم يعتمد على:",
          "108": "•	مستوى الجلوكوز في الدم قبل بدء النشاط البدني. •	كثافة ومدة النشاط. •	أي تغيُّر على جرعات الإنسولين. ",
          "109": "إرشادات عند البدء بالنشاط البدني:",
          "110": "•	البدء بشكل تدريجي، ثم زيادة مدة وكثافة النشاط للوصول إلى المعدل المطلوب والمناسب لكل فرد. •	يجب تهيئة الجسم للنشاط البدني، وذلك بالبدء بتمارين التسخين لمدة 5 إلى 10 دقائق، كما يجب إنهاء الجلسة بتمارين الاسترخاء لمدة 5 إلى 10 دقائق. •	يجب تخصيص وقت للراحة يتراوح ما بين 30 إلى 90 ثانية عند الحاجة إلى ذلك.•	يجب عدم ممارسة النشاط البدني في حالة المرض أو الإصابات الناتجة عن الرياضة. •	يجب استشارة الطبيب قبل ممارسة أي نشاط او المشي على النظام الذي وصي عليه الطبيب خاصتك.",
          "111": "احتياطات عند ممارسة النشاط البدني:",
          "112": "حمل بطاقة تعريف تدل على أن الشخص مصاب بالسكر. شرب سوائل كافية قبل التمرين وأثناءه وبعده للوقاية من الجفاف الذي قد يُخِلُّ بمستويات السكر في الدم. حمل علبة من العصير المُحلَّى أو قطع من السكر أو الحلوى؛ لاستخدامها في حالة هبوط السكر. حمل وجبة خفيفة احتياطية أيضًا إذا كان النشاط البدني سيستمر لأكثر من نصف ساعة. عدم حقن الإنسولين في مناطق الجسم التي سيستخدمها المريض أثناء التمارين؛ لأن استخدام المكان المحقون بالإنسولين في أداء التمارين يسرع من امتصاصه؛ مما قد يعرض الشخص لنوبة هبوط، مثال: تجنب حقن الإنسولين في الفخذ إذا كان المريض سيمارس رياضة المشي. قد يسمح الطبيب بتقليل جرعة الإنسولين قبل ممارسة الرياضة عند الحاجة. تجنب ممارسة النشاط البدني في الأوقات التي يصل فيها مفعول الإنسولين إلى قمة عمله. عند استخدام مضخة الإنسولين يمكن برمجة الضخ المؤقت. يجب قياس نسبة السكر في الدم قبل النشاط البدني وأثناءه وبعده، وأن تستمر المراقبة كل نصف ساعة إذا كان النشاط البدني يستغرق وقتًا أطول؛ وذلك للتدخل السريع عند انخفاض مستوى السكر. ارتداء الأحذية الرياضية المناسبة، والعناية بالقدمين.",
          "113": "بناءاً علي سنك ووزنك ومستوي السكري عندك سوف يقوم الطبيب الخاص بك بتقديم مهام رياضيه المناسبة اليك لتمارسها.",
          "114": "الرياضة",
          "115": "دليل خرائط جوجل  ",
          "116": "سيتم تمييز أقرب المستشفيات ",
          "117": "التالي",
          "118": "تعليمات",
          "119": "والعيادات من موقعك باللون ",
          "120": "الأحمر.",
          "121": "الجلوكوز لدي",
          "122": "تظهر قراءات الجلوكوز بعد مسح المستشعر بنجاح. ابحث عن (1) مستوى الجلوكوز الحالي، (2) سهم اتجاه الجلوكوز، (3) رسم بياني للجلوكوز، و (4) أي رسالة متعلقة بالجلوكوز.",
          "123": "لون خلفية الجلوكوز",
          "124": "يحدد مستوى الجلوكوز الحالي اللون الذي يظهر في الخلفية.",

          "125": "سهم اتجاه الجلوكوز",
          "126": "عند مسح المستشعر، سيشير السهم إلى اتجاه مستوى الجلوكوز الأخير",
          "127": "تطبيق مستشعر جديد",
          "128": "يجب وضع المستشعر على الجزء الخلفي من ذراعك العلوي.",
          "129": "",
          "130": "",
        },
        "en": {
          "1": "Select Language",
          "2": "Email Address",
          "3":
              "We Have a 100k Product , Choose \n Your Product From  Our \n E-commerce Shop",
          "4": "Easy And Safe Paymnet",
          "5": "You can pay in cash \n or through payment gateways",
          "6": "Track Your Order",
          "7":
              "The order can be tracked at every stage \n until it reaches you",
          "8": "Continue",
          "9": "Sign In",
          "10": "Welcome ",
          "11":
              "Sign In Your Email And Password Or  Continue With Social Media",
          "12": "Enter Your Email",
          "13": "Enter Your Password",
          "14": "Forget Password",
          "15": "Sign In",
          "16": "Dont Have An Account ? ",
          "17": "Sign Up",
          "18": "Email",
          "19": "Password",
          "20": "Username",
          "21": "Phone",
          "22": "Enter Your Phone",
          "23": "Enter Your Username",
          "24":
              "Sign Up With Your Email And Password OR Continue With Social Media",
          "25": " have an account ? ",
          "26": "SignIn",
          "27": "Check Email",
          "28": "Account successfully created",
          "29": "please Enter Your Email Address To Recive A verification code",
          "30": "check",
          "31": "Go To Login",
          "32": "Success",
          "33": "save",
          "34": "Please Enter new Password",
          "35": "New Password",
          "36": "Password has been reset successfully",
          "37": "congratulations",
          "38": "successfully registered",
          "39": "Fruits",
          "40": "Vegetables",
          "41": "Nuts",
          "42": "Fish and Meat",
          "43": "Whole grains",
          "44": "Milk and Diary",
          "45": "Oils",
          "46": "Seeds",
          "47": "Saturated Fats",
          "48": "Legumes",
          "49": "Categories",
          "50":
              "Vegetables are food items characterized by their low-fat content, and if present in some varieties, the fats are easily absorbed since they come from fiber. Vegetables are a source of essential carbohydrates that provide the body with energy. They are rich in iron, which is available in legumes. The high water content in vegetables provides numerous benefits to the body, such as facilitating digestion and providing flexibility to body organs. The most important component in vegetables is cellulose, which is not absorbed by the body but remains in the intestines, stimulating their activity. It acts as a natural laxative for the digestive system and stimulates the glands to secrete digestive enzymes",
          "51": "Non-starchy vegetables",
          "52":
              "Non-starchy vegetables are a healthy food choice for people with diabetes. The list of non-starchy vegetables includes broccoli, carrots, artichokes, celery, cucumbers, and onions. Non-starchy vegetables are a good source of dietary fiber, which can generally help slow the absorption of sugar into the bloodstream. They also contain vitamins, minerals, and antioxidants that are beneficial for your overall health. Additionally, they are low in calories and carbohydrates.",
          "53": "Cucumbers",
          "54":
              "Cucumbers are a good vegetable for diabetics who suffer from high blood sugar levels, as they are low in calories and high in fiber content. ",
          "55":
              "Cucumbers may also help lower blood sugar levels because they contain a hormone needed by beta cells to produce insulin.",
          "56": "Tomatoes",
          "57":
              "Tomatoes are a food that does not cause a spike in blood sugar levels. They are also a good source of fiber and vitamins A and C, which are important for diabetics. Dietary fiber helps slow the absorption of sugar into the bloodstream, and vitamins A and C are antioxidants that help protect various cells in the body from damage. For these reasons, tomatoes are among the best foods for diabetics",
          "58": "Broccoli",
          "59":
              " Broccoli contains a compound called sulforaphane, which naturally lowers blood sugar levels. A scientific study concluded that broccoli, which contains sulforaphane",
          "60":
              "reduces markers of oxidative stress and blood sugar levels, and also enhances insulin sensitivity",
          "61": "Spinach",
          "62":
              "Spinach contains many vitamins, fiber, protein, carotene, and minerals that are nutritious for diabetics. The reason you might choose to eat spinach if you have high blood sugar levels is that its glycemic index is zero.",
          "63": "Asparagus",
          "64":
              "Asparagus contains a very low amount of carbohydrates, approximately 7 grams per cup, making it suitable for diabetics who want to lower their blood sugar levels",
          "65": "leafy green vegetables",
          "66":
              "There is a close relationship between consuming two to three servings of leafy green vegetables per week and a reduced likelihood of developing certain types of cancer, heart disease, and diabetes. These vegetables help maintain stable blood sugar levels, and consuming one cup of leafy green vegetables daily can lower the risk of developing diabetes by 14%.",
          "67":
              "Since you are a diabetic, you may wonder if fruit is off-limits for you. The answer is that you can eat certain types of fruit in moderation. Fruit, in general, is a great source of nutrients, fiber, and antioxidants. Here is a list of the top 10 fruits for diabetics: citrus fruits like oranges, apples, berries such as blueberries and cranberries, strawberries, avocados, peaches, plums, cherries, and pears",
          "68": "Berries",
          "69":
              "Berries are fruits rich in vitamins, fiber, and antioxidants, making them beneficial for diabetics as they help improve insulin sensitivity and reduce the amount of glucose in the body. Consuming two cups of berries, equivalent to 250 grams, contributes to lowering blood sugar levels",
          "70": "citrus fruits",
          "71":
              "Fruits like oranges, grapefruits, and other citrus fruits are rich in fiber and plant compounds such as polyphenols and naringenin, which are anti-diabetic. Citrus fruits reduce the risk of developing diabetes because they do not raise blood sugar levels as some other fruits do",
          "72": "Apples",
          "73":
              "Apples contain important plant compounds such as chlorogenic acid and quercetin, which help reduce blood sugar levels and protect the body from developing diabetes.",
          "74": "Consuming nuts may help control blood sugar levels in diabetics, and they are generally one of the best foods for diabetics. Nuts are a good source of protein, fiber, and healthy fats, and they also contain magnesium, a mineral that helps regulate blood sugar levels. Some of the most beneficial types of nuts for diabetics include walnuts, Brazil nuts, cashews, and hazelnuts Although nuts are high in fat and calories, eating them in moderation may help prevent weight gain and keep weight under control and maintain healthy levels",
          "75": "This is often due to the potential ability of nuts to suppress appetite and promote feelings of satiety for longer hours, which may reduce the desire to eat extra amounts of calorie-rich food But it should be noted that nuts should be eaten in moderation, as excessive intake may cause weight gain",
          "76": "Use nuts as a healthy alternative to some high-calorie meals, instead of adding them to the diet as side meals Eat only a moderate serving of nuts a day, and the allowable serving is roughly equivalent to a small handful of nuts in a fist",
          "77": "pistachios ",
          "78": "One study showed that consuming pistachios by individuals with type 2 diabetes may help improve their overall health. This is often attributed to the high magnesium content and a variety of antioxidants found in this type of nut, which may help with the following: Slowing the rate of increase in blood sugar levels after meals Reducing inflammation Suppressing appetite",
          "79": "Walnuts ",
          "80": "Walnuts may have numerous potential benefits for diabetics and individuals looking to reduce their risk of developing diabetes, as studies suggest: One study found that consuming walnuts may help enhance feelings of fullness and promote weight loss, which could contribute to obesity prevention Another study indicated that regular walnut consumption among women may help lower their risk of developing type 2 diabetes The potential benefits of walnuts in this regard are often attributed to their high content of alpha-lipoic acid, an important fatty acid that may help reduce inflammation As a result, this can lower the risk of many chronic diseases that inflammation can exacerbate, such as Alzheimer’s disease, diabetes, and heart disease",
          "81": "Almonds",
          "82": "Giving this type of nut to diabetics may help improve their overall health. One study showed that consuming a small amount of almonds daily for 12 consecutive weeks may help regulate blood sugar levels and reduce the risk of heart disease in individuals with type 2 diabetes",
          "83": "Fish, especially fatty fish (such as salmon, tuna, and sardines), are among the best healthy foods for diabetics for the following reasons: These fish are rich in omega-3 fatty acids, which have been shown to lower blood sugar levels and improve insulin sensitivity Fish are also a good source of protein and low in calories Additionally, they are an excellent source of various vitamins and minerals, including vitamin D, selenium, and magnesium.",
          "84": "The protein found in fish and meat can help you control blood sugar levels and lose weight. Protein also aids in building and repairing tissues in your body. Additionally, protein is an important nutrient for diabetics, as it can help prevent or slow the progression of diabetes complications, such as kidney disease Fish are also beneficial for heart health. Consume heart-healthy fish at least twice a week. Fish such as salmon, mackerel, tuna, and sardines are rich in omega-3 fatty acids, which can protect against heart disease. Avoid eating fried fish and fish that have high levels of mercury, such as cod fish",
          "85": "Low-fat or fat-free dairy products are among the best foods for diabetics, and the American Diabetes Association (ADA) recommends that diabetics consume fat-free or low-fat dairy products. Dairy products are an excellent source of calcium, potassium, and magnesium, and they also contain vitamin A and some B vitamins. Some of the notable low-fat or fat-free dairy products allowed for diabetics include unsweetened almond milk, unsweetened soy milk, low-fat cheese, light cream, fat-free milk and yogurt, and low-fat natural cheeses.",
          "86": "Sources of cholesterol include fatty dairy products, fatty animal proteins, and egg yolks. Do not consume more than 200 mg of cholesterol per day.",
          "87": "Good fats, also known as healthy fats, are essential for a variety of reasons. They help you absorb vitamins, build cell membranes, and produce hormones. Healthy fats also help maintain stable blood sugar levels, which is important if you have diabetes, as unstable blood sugar levels are known to lead to serious health complications Some good sources of healthy fats include canola oil, avocado oil, olive oil, and coconut oil.",
          "88": "Olive oil ",
          "89": "Olive oil plays an important role for diabetics, as it was mentioned in a study that the consumption of olive oil for type II diabetics helps in: Reduce high blood sugar level. Improvement of blood insulin levelling. Enhance glucose tolerance. Improve insulin sensitivity in the blood. Reduce cellular death of cells responsible for insulin production Increase the number of cells responsible for the manufacture of insulin.",
          "90": "Coconut oil ",
          "91": "Coconut oil stimulates insulin production and reduces insulin resistance levels in the body. It helps maintain stable blood sugar levels and encourages the body to utilize blood glucose more effectively. Therefore, coconut oil may help prevent diabetes or improve a diabetic patient's ability to keep their condition under control, especially for those with type 2 diabetes.",
          "92": "Whole grains are an important part of a healthy diet for diabetics, as they are rich in fiber and various nutrients and can help control blood sugar levels. Whole grains include whole wheat, brown rice, oats, barley, quinoa, wild rice, buckwheat, bulgur (cracked wheat), and millet. It's worth noting that consuming foods high in dietary fiber is one of the ways to maintain digestive health. It is important to note that carbohydrates, such as starch found in grains, have the greatest impact on blood sugar levels because all carbohydrates are ultimately broken down into simple sugars by the body. The body takes longer to digest complex carbohydrates and convert them into simple sugars, making them a better option for everyone, including diabetics. Experts recommend that individuals with blood sugar level issues limit their carbohydrate intake to maintain healthy blood sugar levels; however, it is not advisable to eliminate grains entirely from the daily diet due to the benefits of consuming carbohydrates in a balanced diet. Here are the key benefits of whole grains for diabetics: - Reducing the risk of developing type 2 diabetes. - Controlling blood sugar levels.  - Lowering the chances of developing diabetes.",
          "93": "Whole wheat grains",
          "94": "Consuming whole wheat grains helps regulate blood sugar levels and keep them within normal and healthy ranges due to their relatively low glycemic index. Whole grains are high in dietary fiber, and fiber is a type of carbohydrate that can improve blood sugar levels for the following reasons:  - The difficulty the body has in digesting fiber can slow down digestion and the absorption of nutrients from food, thus preventing sudden spikes in blood sugar and maintaining sugar levels within a healthy range.  The potential of fiber to improve insulin sensitivity in the body.  Whole wheat grains are also a good source of various minerals and vitamins, such as B vitamins, vitamin E, zinc, and magnesium.",
          "95": "Oats and Brown rice",
          "96": "Oats help lower blood sugar levels by increasing insulin sensitivity, which is one of the main benefits of oats for kidney patients. Brown rice is one of the beneficial whole grains for diabetics as it:- Promotes heart health. - Helps manage diabetes. - May play a role in weight loss. - Improves overall body health. - Is a gluten-free source.   ",
          "97": "However, if you want to try following a gluten-free diet, there is no reason to give up grains. Experts recommend that most people with blood sugar problems consume whole grains, as they are nutritious and high in dietary fiber, which helps maintain healthy blood sugar levels. Coriander seeds help maintain stable blood sugar levels in diabetics by controlling the secretion of insulin in the body. Different seeds have various effects on blood sugar levels. Some, like chia seeds and flax seeds, can help control blood sugar levels, while others, like pumpkin seeds and sunflower seeds, can cause an increase in blood sugar. Therefore, if you have diabetes, it is important to monitor your seed intake and choose seeds that do not raise blood sugar levels.  Flax seeds can enhance the effects of blood sugar-lowering medications taken by diabetics, which can be very harmful. Therefore, you should avoid consuming flax seeds.   ",
          "98": "Some people ask whether legumes raise blood sugar. It is important to know that legumes such as beans, peas, and lentils have a low glycemic index (GI), which means they have a slow impact on blood sugar levels.  Among the most beneficial legumes for diabetics are chickpeas, black-eyed peas, and beans.  Legumes can sometimes cause an increase in blood sugar levels because they contain a significant amount of carbohydrates. Therefore, diabetics should pay attention to their diet, especially when including legumes.  It is recommended to combine legumes with non-starchy vegetables, low-sugar fruits, and protein-rich foods to create an ideal meal without affecting blood sugar levels.",
          "99": "Red beans and Chickpeas",
          "100": "Red beans are beneficial for diabetics, as their rich nutritional content, especially fiber, helps regulate blood sugar levels, keeping them under control and preventing sudden spikes. Chickpeas are also very beneficial for diabetics. Their low glycemic index makes them suitable for maintaining blood sugar levels even in diabetics. Chickpeas contain a high amount of fiber and slow-digesting sugars, as well as a high content of proteins, calcium, potassium, and folic acid.",
          "101": "Meals with saturated fats",
          "102": "Diabetes increases the risk of blocked and hardened arteries, making you more susceptible to heart disease and stroke. Foods containing the following elements can hinder your efforts to maintain a heart-healthy diet: Saturated fats: Avoid fatty dairy products and fatty animal proteins, such as butter, beef, sausages, and bacon. Also, limit your intake of coconut and palm kernel oils. Trans fats: Avoid trans fats found in ready-made snack foods, baked goods, shortening, and solid margarine. Cholesterol: Sources of cholesterol include fatty dairy products, fatty animal proteins, egg yolks, liver, and other organ meats. Do not consume more than 200 mg of cholesterol per day. Sodium: Do not consume more than 2,300 mg of sodium per day. Your doctor may suggest a lower amount if you have high blood pressure.",
          "103": "Sports system instructions",
          "104": "Engaging in regular physical activity has numerous positive effects and benefits on human health, especially for those with diabetes, as it is a key factor in regulating blood sugar levels. The type of exercise varies depending on age, gender, health condition, and individual ability, and your doctor will monitor your physical condition to determine the appropriate exercises for you.",
          "105": "Benefits of physical activity for individuals with diabetes:",
          "106": "•	Lowering and regulating blood sugar and fat levels.  •	Reducing the body's resistance to insulin.   •	Increasing the number of insulin receptors, thereby optimizing the use of insulin in the body.  •	Reducing the amount of medication the patient needs.  •	Strengthening and building the body and muscles.  •	Helping with weight loss and maintaining an ideal weight.  •	Improving mental well-being.",
          "107": "The impact of physical activity on blood sugar depends on:",
          "108": "•	Blood glucose level before starting physical activity.   •	Intensity and duration of the activity.  •	Any changes in insulin doses.",
          "109": "Guidelines for starting physical activity:",
          "110": "•	Start gradually, then increase the duration and intensity of the activity to reach the desired and appropriate level for each individual. •	Prepare the body for physical activity by starting with warm-up exercises for 5 to 10 minutes, and end the session with relaxation exercises for 5 to 10 minutes. •	Allocate rest periods ranging from 30 to 90 seconds when needed. •	Avoid physical activity in case of illness or sports-related injuries. •	Consult your doctor before engaging in any activity or following the regimen recommended by your physician.",
          "111": "Precautions when engaging in physical activity:",
          "112": "Carry an identification card indicating that the person has diabetes.  Drink enough fluids before, during, and after exercise to prevent dehydration, which can affect blood sugar levels. Carry a small juice box, sugar cubes, or candy to use in case of low blood sugar.  Also, carry a backup snack if the physical activity will last more than half an hour.   Avoid injecting insulin into areas of the body that will be used during exercise, as using the injected area can speed up insulin absorption, potentially leading to a hypoglycemic episode. For example, avoid injecting insulin into the thigh if walking is planned.  The doctor may allow a reduction in the insulin dose before exercise if necessary.  Avoid physical activity during times when insulin action is at its peak.  When using an insulin pump, temporary basal rate programming can be used.  Blood sugar levels should be checked before, during, and after physical activity, and monitored every half hour if the activity lasts longer to ensure quick intervention in case of low blood sugar.  Wear appropriate athletic shoes and take care of your feet.",
          "113": "Based on your age, weight, and level of diabetes, your doctor will provide you with suitable exercise tasks to engage in.",
          "114": "sports",
          "115": "Google Maps Guide",
          "116": "   The most near hospitals and clinics from your location will be highlighted with red colour",
          "117": "Next",
          "118": "Instructions",
          "119": "",
          "120": "",
          "121": "My Glucose ",
          "122": "Your glucose readings appears after successfully scanning your sensor look for (1) current glucose, (2) glucose trend arrow, (3) glucose graph, and (4) any glucose message",
          "123": "Glucose back ground color",
          "124": "Your current glucose determines which color is shown behind it",
          "125": "Glucose trend arrow ",
          "126": "When you scan your sensor, an arrow will indicate your recent glucose trend",
          "127": "Apply a new sensor.",
          "128": "The sensor should be applied to the back of your upper arm",
          "129": "",
          "130": "",
        }
      };
}
